### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ttaylor29** [cplotts/snoopwpf#121]
I am trying to use Spoof and this is the error I see when I go to the magiffying glass. 

I'm trying to get some color codes of a tab text on a dev express tab control. 

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile) in\snoopwpf-master\snoopwpf-master\Snoop\Injector.cs:line 35
   at Snoop.WindowInfo.Magnify() in \snoopwpf-master\snoopwpf-master\Snoop\WindowInfo.cs:line 215

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.16299
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
As it looks like you compiled snoop on your own machine, have you compiled all projects from the Snoop.sln?

**Comment by ttaylor29** [comment]
Let me try that.

Is there a way I can just get the main .exe and use it?

**Comment by ttaylor29** [comment]
Hey batzen,

I ran off of snoop.sln and now it is working :-)

**Comment by batzen** [comment]
Nice you found it. 😉
Snoop consists of multiple dlls and exes to do it's job. Without those it wouldn't be possible to inject snoop into a running process or support multiple .net runtimes etc..

**Comment by ttaylor29** [comment]
Thanks buddy.
