### ISSUE TITLE
OpenClipboard exception when closing Snoop

### ISSUE THREAD

**Issue by LordCheese** [cplotts/snoopwpf#31]
Hi Snoop team!

I've been using Snoop for a couple of weeks now, and I've suddenly started encountering this error when I try and close a Snoop window for my WPF application. 

Exception: 
Message: OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
Stacktrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Snoop.EditedPropertiesHelper.DumpObjectsWithEditedProperties()
   at Snoop.SnoopUI.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

![image](https://cloud.githubusercontent.com/assets/2198696/5741710/72bf692e-9bd2-11e4-9548-58afaeb86972.png)

Please let me know if there's any info you need.

Thanks,

Chris Dusyk

**Comment by nwolverson** [comment]
Snoop tries to copy changes to the clipboard on closing. Windows clipboard operations can fail (program has clipboard open), probably this should just be suppressed if not retry first. Can ignore this if it's not too annoying.

Duplicates #12 #14. Some ideas http://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid

**Comment by LordCheese** [comment]
Ah, I see. It only happens occasionally so it's not a major issue. Thank you for your help!
