### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by XplittR** [cplotts/snoopwpf#62]
`Message: OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
Stacktrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Snoop.EditedPropertiesHelper.DumpObjectsWithEditedProperties()
   at Snoop.SnoopUI.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by cplotts** [comment]
It would have happened when closing the main Snoop window (i.e. not the app chooser). That is when we copied the modified properties to the clipboard.

Regardless this functionality was removed ... at least when we close the window. Now the user has to manually do it with Ctrl-Shift-C. In other words, you won't likely see this issue ... unless you are doing that ... and taking advantage of this functionality (one of the many hidden tricks in Snoop).

Given that, I'm going to close for now. If you see it again, and especially if you get a reliable repro, let me know.
