### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by s0ndos** [cplotts/snoopwpf#94]
Could never get this application to work

Exception details:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Snoop.Injector.Launch(IntPtr windowHandle, Assembly assembly, String className, String methodName) in D:\Programs\snoopwpf\Snoop\Injector.cs:line 69
   at Snoop.WindowInfo.Snoop() in D:\Programs\snoopwpf\Snoop\AppChooser.xaml.cs:line 304

---
### Environment
- Snoop 2.10.0.0
- Windows 6.1.7601
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Did you compile snoop yourself?

**Comment by s0ndos** [comment]
It's okay, I got it working. I can't recall what the issue was and I wasn't
sure how to remove the issue I created. You can close this one. Thank you!
